name: Salesforce CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@v2

    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Retrieve key file from Azure Key Vault
      id: retrieve-key
      run: |
          az keyvault secret download --vault-name ${{ secrets.KEY_VAULT_NAME }} --name cicd1 --file salesforce-dev-qa.key

    - name: Retrieve JWT Key from Azure Key Vault
      run: |
          az keyvault secret download --vault-name ${{ secrets.KEY_VAULT_NAME }} --name cicd1 --file jwt.key

    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd

