name: Salesforce Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  VlocityDeployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Azure CLI Action
        uses: Azure/cli@v2.0.0
        with:
          inlineScript: |
             az --version
  
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Retrieve key file content from Azure Key Vault
        id: retrieve-key
        run: |
          secret_value=$(az keyvault secret show --vault-name ${{ secrets.KEY_VAULT_NAME }} --name salesforce-auth --query value -o tsv)
          echo "$secret_value" > salesforce-dev-qa.key
            
      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli --global

      - name: Install Vlocity Build Tool
        run: npm install -g vlocity

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Authenticate with Salesforce
        run: |
          jwt_key_file="salesforce-dev-qa.key"
          client_id="${{ secrets.CLIENT_ID }}"
          user_name="${{ secrets.USER_NAME }}"
          login_url="${{ secrets.LOGIN_URL }}"
        
          echo "Authenticating with Salesforce..."
          sfdx force:auth:jwt:grant --clientid $client_id --jwtkeyfile $jwt_key_file --username $user_name --instanceurl $login_url 

      - name: Verify Salesforce Connection
        id: verify_connection
        run: |
          sfdx force:org:display -u ${{ secrets.USER_NAME }}

      - name: Deploy source code to DeployTestOrg Org
        run: |
          sfdx force:source:deploy -p force-app -w 10 -u ${{ secrets.USER_NAME }}

      - name: Deploy Vlocity Components using Manifest
        run: |
          vlocity packDeploy -job flexpage.project.yaml -sfdx.username ${{ secrets.USER_NAME }}
