name: Salesforce JWT Authentication

on:
  push:
    branches:
      - main

jobs:
  VlocityDeployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Azure CLI Action
        uses: Azure/cli@v2.0.0
        with:
          inlineScript: |
             az --version
  
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Retrieve key file from Azure Key Vault
        id: retrieve-key
        run: |
          az keyvault secret download --vault-name ${{ secrets.KEY_VAULT_NAME }} --name salesforce-dev-qa --query value -o tsv > secret.key

      - name: Display the key (optional, for debugging purposes)
        run: |
          cat secret.key
        # Use this step to verify the content of the key file. Remove or comment out this step in production.

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli --global

      - name: Install Vlocity Build Tool
        run: npm install -g vlocity

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Authenticate with Salesforce
        run: |
          jwt_key_file="server.key"
          client_id="${{ secrets.CLIENT_ID }}"
          user_name="${{ secrets.USER_NAME }}"
          login_url="${{ secrets.LOGIN_URL }}"
        
          echo "Authenticating with Salesforce..."
          sfdx force:auth:jwt:grant --clientid $client_id --jwtkeyfile secret.key --username $user_name --instanceurl $login_url 

      - name: Verify Salesforce Connection
        id: verify_connection
        run: |
          sfdx force:org:display -u bxkumar1@sentara.com.cicd2

      - name: Deploy source code to DeployTestOrg Org
        run: |
          sfdx force:source:deploy -p force-app -w 10 -u bxkumar1@sentara.com.cicd2

      - name: Deploy Vlocity Components using Manifest
        run: |
          vlocity packDeploy -job flexpage.project.yaml -sfdx.username bxkumar1@sentara.com.cicd2
