name: Salesforce CICD Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - Dev
          - QA

jobs:
  VlocityDeployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli --global
    
      - name: Install Vlocity Build Tool
        run: npm install -g vlocity

      - name: Authorize Salesforce Org
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Dev" ]; then
            sfdx force:auth:jwt:grant --clientid YOUR_CLIENT_ID --jwtkeyfile mycerts/server.key --username dev-username@example.com --instanceurl https://your-instance-url
          elif [ "${{ github.event.inputs.environment }}" == "QA" ]; then
            sfdx force:auth:jwt:grant --clientid YOUR_CLIENT_ID --jwtkeyfile mycerts/server.key --username qa-username@example.com --instanceurl https://your-instance-url
          fi
    
      - name: Verify Salesforce Connection
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Dev" ]; then
            sfdx force:org:display -u dev-username@example.com
          elif [ "${{ github.event.inputs.environment }}" == "QA" ]; then
            sfdx force:org:display -u qa-username@example.com
          fi

      - name: Deploy Vlocity Components using Manifest
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Dev" ]; then
            vlocity packDeploy -job flexpage.project.yaml -sfdx.username dev-username@example.com
          elif [ "${{ github.event.inputs.environment }}" == "QA" ]; then
            vlocity packDeploy -job flexpage.project.yaml -sfdx.username qa-username@example.com
          fi
