name: Deploy on commit

on:
  push:
    branches:
      - main

jobs:
  VlocityDeployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli --global
    
      - name: Install Vlocity Build Tool
        run: npm install -g vlocity

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Authorize Salesforce DeployTestOrg Org
        run: |
         sfdx force:auth:jwt:grant --clientid 3MVG9NYvTkhtdEI5Z9dZmBB.toZ_f9ZTkCtyPmQsts6QEJINuMe.ywRNgQcUztn1n6Aw8r8OZ0uJHhAIos7nX --jwtkeyfile SSL/server.key --username bxkumar1@sentara.com.cicd2 --instanceurl https://sentarahealth--cicd2.sandbox.my.salesforce.com 
    
      - name: Verify Salesforce Connection
        id: verify_connection
        run: |
          sfdx force:org:display -u bxkumar1@sentara.com.cicd2

      - name: Get Latest Commit and Folder in vlocity
        id: get_latest_commit_folder
        run: |
          latest_commit=$(git log -1 --pretty=format:"%H" -- vlocity)
          latest_folder=$(git diff-tree --no-commit-id --name-only -r $latest_commit | grep 'vlocity/' | head -n 1 | xargs dirname)
          echo "Latest vlocity folder: $latest_folder"
          echo "::set-output name=latest_folder::$latest_folder"
        shell: bash

      - name: Deploy Vlocity Components using Manifest
        run: |
          vlocity -projectPath ${{ steps.get_latest_commit_folder.outputs.latest_folder }} -job VlocityJobFile.yml -sfdx.username bxkumar1@sentara.com.cicd2
        env:
          projectPath: ${{ steps.get_latest_commit_folder.outputs.latest_folder }}
