name: Retrieve Azure Key Vault Secret

on: 
  workflow_dispatch:
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Azure CLI Action
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
           az --version

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Retrieve key file from Azure Key Vault
        id: retrieve-key
        run: |
          az keyvault secret download --vault-name ${{ secrets.KEY_VAULT_NAME }} --name salesforce-dev-qa

    - name: Display the secret value
      run: echo "The secret value is ${{ steps.get-secret.outputs}}

    - name: Print 
      run: cat ${{ steps.get-secret.outputs}}
