name: Retrieve Azure Key Vault Secret

on: 
  workflow_dispatch:
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Azure CLI Action
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
           az --version

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - name: Retrieve key file from Azure Key Vault
    #   id: retrieve-key
    #   run: |
    #       az keyvault secret download --vault-name ${{ secrets.KEY_VAULT_NAME }} --name cicd1 --file salesforce-dev-qa.key

    - name: Retrieve key file content from Azure Key Vault
      id: retrieve-key
      run: |
         secret_value=$(az keyvault secret show --vault-name ${{ secrets.KEY_VAULT_NAME }} --name salesforce-dev --query value -o tsv)
         echo "$secret_value" > salesforce-dev-qa.key
        
    - name: List files in directory
      run: ls -la
   
    - name: Validate JWT key with OpenSSL
      run: |
        chmod 600 salesforce-dev-qa.key
        openssl rsa -in salesforce-dev-qa.key -check
  
    - name: Display the secret value
      run: cat salesforce-dev-qa.key